[package]
name = "day_01"
version = "0.1.0"
edition = "2021"

[profile.bench]
lto = true
opt-level = "s"

[dependencies]
serde = "1.0"
serde_json = "1.0"
itertools = "0.12"
color-eyre = "0.6.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false